### ISSUE TITLE
Explore ways to not query for every feature

### ISSUE THREAD

**Issue by steveoh** [Esri/cluster-layer-js#12]
https://github.com/Esri/cluster-layer-js/blob/master/src/clusterfeaturelayer.js#L470-L483

``` js
                if (uncached.length > this._returnLimit) {
                    while(uncached.length) {
                        // Improve performance by just passing list of IDs
                        this._query.objectIds = uncached.splice(0, this._returnLimit - 1);
                        queries.push(this.queryTask.execute(this._query));
                    }
                    all(queries).then(lang.hitch(this, function(res) {
                        var features = arrayUtils.map(res, function(r) {
                            return r.features;
                        });
                        this._onFeaturesReturned({
                            features: merge(features)
                        });
                    }));
```

really puts the rage on an arcgis server that has more than a good demos worth of features. I sort of figured that `returnLimit` would act on a feature layer's virtual grid instead of doing snap shot style spin up a query task to download every feature - In our case being 15mb's gzipped. Should this cluster layer inherit from FeatureLayer to get access to the virtual grid instead of graphics layer? 

In the future there is going to have to be server side point clustering to handle these scenarios. Are you in the loop enough to know if that is on the right peoples radar?

**Comment by alaframboise** [comment]
Yip, I'm in the loop. I will let you know if this is on the radar.

**Comment by steveoh** [comment]
I have taken this project and turned it into something that expects 1 compressed json file of the [id's, x, y], and lazy queries for attributes and what not when requested. It is working well so far for 200K points. We came to the conclusion that for point clustering to be honest, we needed to cluster every point. Making n number of requests at the max result count was too many requests. One large cacheable file seemed like the best tradeoff.

**Comment by odoe** [comment]
Maybe a `hardLimit` property that would limit queries in each pass? With tons of points like wouldn't even a virtual grid chew up the requests? I like your solution @steveoh. It wouldn't be too difficult to set the layer up so that if it was provided the data, not to make the HTTP requests.

**Comment by alaframboise** [comment]
I'm open to branching this and experimenting for sure. I also like the idea of experimenting with server-side clustering. The backend or some nodejs middleware component could probably crank this out a lot faster than delivering 1000's of points to client.

**Comment by steveoh** [comment]
SOI's could work but they might be too slow.
