### ISSUE TITLE
"Styled" sample using inaccessible layer

### ISSUE THREAD

**Issue by jpeterson** [Esri/cluster-layer-js#19]
The "styled" example in the `gh-pages` branch is using a service that throws a "token required" error.

https://github.com/Esri/cluster-layer-js/blob/gh-pages/styled.html#L241

Service URL:
http://services1.arcgis.com/EwZCWiHAzgPcnGng/arcgis/rest/services/Magnitude_7_Earthquakes/FeatureServer/0

**Comment by jtroe** [comment]
*bump*

**Comment by alaframboise** [comment]
All fixed a while back. Thanks guys!
