### ISSUE TITLE
webpack / typings / Arcgis 3.18 / Angular2

### ISSUE THREAD

**Issue by klanglie** [Esri/cluster-layer-js#36]
Our project relies on ClusterLayer. It was working when we were using SystemJS and Visual Studio. Now that we have separated the front end from the back end and use VS Code primarily as our front-end editor, ClusterLayer no longer works. We are also now using webpack.  We are having a hard time getting ClusterLayer.js to work in 3.18 with our new configuation. After creating a typings file for it, tsc compiles and the site runs without error. However, for some reason no clusters are showing up. Can you offer any advice or do you know of anyone who has a similar setup to ours that we could use to help us along? Thanks,
Kai

**Comment by andygup** [comment]
@PivotalAnimal While not specific to ClusterLayer, I recommend taking a look at this blog post on using the [ArcGIS JS API with webpack](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/). There may be some tidbits in there that are helpful to your specific issues.

**Comment by klanglie** [comment]
Issue solved. Thanks!
