### ISSUE TITLE
showing singles regardless of showSingles param

### ISSUE THREAD

**Issue by derekwmiller** [Esri/cluster-layer-js#43]
singles are currently being drawn regardless of the showSingles value.

**Comment by derekwmiller** [comment]
I should learn to read... 
 //     showSingles:    Boolean?
//         Optional. Whether or graphics should be displayed when a cluster graphic is clicked. Default is true.

this is a non-issue

**Comment by jgravois** [comment]
if you could spare the time to submit a PR with any pearls of wisdom to clarify the points that initially confused you, i can make sure it lands.

**Comment by derekwmiller** [comment]
This issue was totally on me. Not sure it needs any further clarification.
